module.exports = {
  openapi: '3.0.0',
  info: {
    title: 'Tawsila',
    version: '1.0.0',
    description: 'Test Express API with autogenerated swagger doc',
  },
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'Bearer',
      },
    },
  },
  schemes: ['https'],
  security: [
    {
      bearerAuth: [],
    },
  ],
};
